[package]
name = "existential"
version = "0.1.0"
authors = ["Newton Ni <nwtnni@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.26"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.44"
ureq = { version = "0.11.3", features = ["json"] }
